/**
 * @fileoverview gRPC-Web generated client stub for grewal
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: home_general.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.grewal = require('./home_general_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.grewal.HomeGeneralClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.grewal.HomeGeneralPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grewal.HomeGeneralRequest,
 *   !proto.grewal.HomeGeneralResponse>}
 */
const methodDescriptor_HomeGeneral_GetHomeGeneral = new grpc.web.MethodDescriptor(
  '/grewal.HomeGeneral/GetHomeGeneral',
  grpc.web.MethodType.UNARY,
  proto.grewal.HomeGeneralRequest,
  proto.grewal.HomeGeneralResponse,
  /**
   * @param {!proto.grewal.HomeGeneralRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grewal.HomeGeneralResponse.deserializeBinary
);


/**
 * @param {!proto.grewal.HomeGeneralRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.grewal.HomeGeneralResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.grewal.HomeGeneralResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.grewal.HomeGeneralClient.prototype.getHomeGeneral =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/grewal.HomeGeneral/GetHomeGeneral',
      request,
      metadata || {},
      methodDescriptor_HomeGeneral_GetHomeGeneral,
      callback);
};


/**
 * @param {!proto.grewal.HomeGeneralRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.grewal.HomeGeneralResponse>}
 *     Promise that resolves to the response
 */
proto.grewal.HomeGeneralPromiseClient.prototype.getHomeGeneral =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/grewal.HomeGeneral/GetHomeGeneral',
      request,
      metadata || {},
      methodDescriptor_HomeGeneral_GetHomeGeneral);
};


module.exports = proto.grewal;

