---
- name: Ensure grewal-backend systemd unit file is deployed
  ansible.builtin.template:
    src: grewal-backend.service.j2
    dest: /etc/systemd/system/grewal-backend.service
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd and restart grewal-backend

# roles/grewal-backend/tasks/main.yml (Add this task)
# ... other tasks to setup/start grewal-backend ...

- name: Place Consul service definition for grewal-backend
  ansible.builtin.template:
    src: grewal-backend-service.hcl.j2
    dest: "/etc/consul.d/grewal-backend-service.hcl"
    owner: root 
    group: root
    mode: '0644'
  notify: Reload Consul Configuration

- name: Ensure grewal-backend service is started and enabled
  ansible.builtin.systemd:
    name: grewal-backend.service
    state: started
    enabled: yes
