authz_service_image_repository: "grewal/authz-service"
authz_service_image_tag: "v0.6.2"

authz_service_http_port: 9001 # Host port for HTTP access for Envoy
authz_service_http_port_container: 9001 # for HTTP INSIDE container

authz_service_grpc_port: 9002 # Host port for gRPC access for Envoy
authz_service_grpc_port_container: 9002 # for gRPC INSIDE container

authz_service_log_level: "INFO"
consul_host_ip: "10.128.0.22"
consul_http_port: 8500
redis_port: 6379
