---
# tasks file for node_exporter role (ansible/roles/node_exporter/tasks/main.yml)

- name: Pull Node Exporter Docker image
  community.docker.docker_image:
    name: "quay.io/prometheus/node-exporter"
    tag: "v1.9.1"
    source: pull
  become: yes

- name: Create Node Exporter systemd service file
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Reload systemd daemon

- name: Ensure Node Exporter service is enabled and started
  ansible.builtin.systemd:
    name: node_exporter.service
    enabled: yes
    state: started
  become: yes
