---
# tasks/main.yml for consul role

- name: Ensure Consul config directory exists
  ansible.builtin.file:
    path: /etc/consul.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Ensure Consul host data directory exists
  ansible.builtin.file:
    path: /opt/consul/data
    state: directory
    owner: '100'  # consul user UID inside container
    group: '1000' # consul user GID inside container
    mode: '0750'
  become: yes

- name: Deploy Consul HCL configuration file
  ansible.builtin.template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Restart consul service # Handler for HCL config changes

- name: Deploy Consul systemd unit file
  ansible.builtin.template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: # Handlers for systemd unit file changes
    - Reload systemd daemon
    - Restart consul service

- name: Ensure Consul service is started and enabled
  ansible.builtin.systemd:
    name: consul.service
    state: started
    enabled: yes
  become: yes
