---
# ansible/roles/consul/tasks/main.yml

- name: Pull the specified Consul Docker image
  community.docker.docker_image:
    name: "{{ consul_docker_image_repository }}:{{ consul_docker_image_tag }}"
    source: pull
  become: yes

- name: Ensure Consul config directory exists
  ansible.builtin.file:
    path: /etc/consul.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Ensure Consul host data directory exists
  ansible.builtin.file:
    path: /opt/consul/data
    state: directory
    owner: '100'
    group: '1000'
    mode: '0750'
  become: yes

- name: Deploy Consul HCL configuration file
  ansible.builtin.template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Restart consul service

- name: Deploy Consul systemd unit file
  ansible.builtin.template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Restart consul service

- name: Ensure Consul service is started and enabled
  ansible.builtin.systemd:
    name: consul.service
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
