[workspace]
members = ["initlock-ebpf"]

[package]
name = "initlock"
version = "0.1.0"
edition = "2021"

[dependencies]
aya = { version = "0.13", features = ["async_tokio"] }
aya-log = "0.2"
clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1.35", features = ["full", "rt", "rt-multi-thread", "macros", "signal"] }
anyhow = "1.0"
env_logger = "0.10"
log = "0.4"
libc = "0.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
