---
# tasks file for authz_service role

# 1. Ensure dependent directories exist (Consul config dir)
- name: Ensure Consul config directory exists for service definition
  ansible.builtin.file:
    path: "/etc/consul.d"
    state: directory
    mode: '0755'
  become: yes # Assuming root needed for /etc/consul.d

# 2. Deploy Consul service definition for authz-service
- name: Deploy Consul service definition for authz-service
  ansible.builtin.template:
    src: authz-service.hcl.j2
    dest: "/etc/consul.d/authz-service.hcl"
    owner: consul
    group: consul
    mode: '0644'
  become: yes # Needed to write to /etc/consul.d
  notify: Reload Consul Configuration

# 3. Ensure authz-service container is running using the specified tag
- name: Ensure authz-service container is running
  community.docker.docker_container:
    name: authz-service
    image: "grewal/authz-service:{{ authz_service_image_tag }}"
    state: started         # Ensure container is running
    pull: true             # Always attempt to pull the specified image tag
    recreate: true         # Recreate container if image or config differs from definition
    network_mode: host     # Use host networking
    restart_policy: always # Automatically restart if it stops/crashes
    env:                   # Environment variables
      CONSUL_HTTP_ADDR: "127.0.0.1:8500"
      LISTEN_ADDR: ":{{ authz_service_listen_port | default(9001) }}"
      REDIS_ADDR: "{{ authz_service_redis_addr | default('127.0.0.1:6379') }}"
      REDIS_PASSWORD: "{{ redis_password }}"
    labels:
      service: authz-service
      managed_by: ansible
  become: no
