---
# tasks file for authz_service role

- name: Ensure Consul config directory exists for service definition
  ansible.builtin.file:
    path: "/etc/consul.d"
    state: directory
    mode: '0755'
  become: yes

- name: Deploy Consul HTTP service definition for authz-service
  ansible.builtin.template:
    src: authz-service-http.hcl.j2
    dest: "/etc/consul.d/authz-service-http.hcl" # Deploys as authz-service-http.hcl
    owner: consul
    group: consul
    mode: '0644'
  become: yes
  notify: Reload Consul Configuration

- name: Deploy Consul gRPC service definition for authz-service
  ansible.builtin.template:
    src: authz-service-grpc.hcl.j2
    dest: "/etc/consul.d/authz-service-grpc.hcl" # Deploys as authz-service-grpc.hcl
    owner: consul
    group: consul
    mode: '0644'
  become: yes
  notify: Reload Consul Configuration

# Ensure your docker_container task for authz-service is here and correctly
# uses authz_service_image_tag, publishes both host ports (e.g., 9001 and 9002),
# and sets necessary environment variables for the container.
# The container itself should listen on its internal ports (e.g., 9001 for HTTP, 9002 for gRPC).
- name: Ensure authz-service container is running
  community.docker.docker_container:
    name: authz-service
    image: "grewal/authz-service:{{ authz_service_image_tag }}" # Should be v0.2.0
    state: started
    pull: true
    recreate: true # Important to pick up port changes if any
    network_mode: grewalnet 
    ports:
      # Publish container's HTTP port (e.g., 9001) to host's 127.0.0.1:{{ authz_service_http_port }}
      - "127.0.0.1:{{ authz_service_http_port | default(9001) }}:{{ authz_service_http_port_container | default(9001) }}"
      # Publish container's gRPC port (e.g., 9002) to host's 127.0.0.1:{{ authz_service_grpc_port }}
      - "127.0.0.1:{{ authz_service_grpc_port | default(9002) }}:{{ authz_service_grpc_port_container | default(9002) }}"
    restart_policy: always
    env:
      CONSUL_HTTP_ADDR: "{{ consul_host_ip }}:{{ consul_http_port | default(8500) }}"
      HTTP_LISTEN_ADDR: ":{{ authz_service_http_port_container | default(9001) }}"
      GRPC_LISTEN_ADDR: ":{{ authz_service_grpc_port_container | default(9002) }}"
      REDIS_ADDR: "redis-server:{{ redis_port | default(6379) }}"
      REDIS_PASSWORD: "{{ redis_password }}"
      LOG_LEVEL: "{{ authz_service_log_level | default(\"INFO\") }}"
    labels:
      service: authz-service
      managed_by: ansible
  become: no
