---
- name: Reload systemd and restart consul # This name MUST match the notify: in the task
  ansible.builtin.systemd:
    name: consul
    state: restarted
    daemon_reload: yes # Combine daemon-reload and restart
  become: yes
