---
# handlers/main.yml for consul role

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: Restart consul service
  ansible.builtin.systemd:
    name: consul.service # Explicitly use .service suffix
    state: restarted
  become: yes
