---
# ansible/roles/consul/handlers/main.yml

- name: Restart consul service
  ansible.builtin.systemd:
    name: consul.service
    state: restarted
    daemon_reload: yes # This handles both daemon-reload and restart in one step
  become: yes
