// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: home_general.proto

#include "home_general.pb.h"
#include "home_general.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace grewal {

static const char* HomeGeneral_method_names[] = {
  "/grewal.HomeGeneral/GetHomeGeneral",
};

std::unique_ptr< HomeGeneral::Stub> HomeGeneral::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< HomeGeneral::Stub> stub(new HomeGeneral::Stub(channel, options));
  return stub;
}

HomeGeneral::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetHomeGeneral_(HomeGeneral_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status HomeGeneral::Stub::GetHomeGeneral(::grpc::ClientContext* context, const ::grewal::HomeGeneralRequest& request, ::grewal::HomeGeneralResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::grewal::HomeGeneralRequest, ::grewal::HomeGeneralResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetHomeGeneral_, context, request, response);
}

void HomeGeneral::Stub::async::GetHomeGeneral(::grpc::ClientContext* context, const ::grewal::HomeGeneralRequest* request, ::grewal::HomeGeneralResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::grewal::HomeGeneralRequest, ::grewal::HomeGeneralResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetHomeGeneral_, context, request, response, std::move(f));
}

void HomeGeneral::Stub::async::GetHomeGeneral(::grpc::ClientContext* context, const ::grewal::HomeGeneralRequest* request, ::grewal::HomeGeneralResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetHomeGeneral_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::grewal::HomeGeneralResponse>* HomeGeneral::Stub::PrepareAsyncGetHomeGeneralRaw(::grpc::ClientContext* context, const ::grewal::HomeGeneralRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::grewal::HomeGeneralResponse, ::grewal::HomeGeneralRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetHomeGeneral_, context, request);
}

::grpc::ClientAsyncResponseReader< ::grewal::HomeGeneralResponse>* HomeGeneral::Stub::AsyncGetHomeGeneralRaw(::grpc::ClientContext* context, const ::grewal::HomeGeneralRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetHomeGeneralRaw(context, request, cq);
  result->StartCall();
  return result;
}

HomeGeneral::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HomeGeneral_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HomeGeneral::Service, ::grewal::HomeGeneralRequest, ::grewal::HomeGeneralResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HomeGeneral::Service* service,
             ::grpc::ServerContext* ctx,
             const ::grewal::HomeGeneralRequest* req,
             ::grewal::HomeGeneralResponse* resp) {
               return service->GetHomeGeneral(ctx, req, resp);
             }, this)));
}

HomeGeneral::Service::~Service() {
}

::grpc::Status HomeGeneral::Service::GetHomeGeneral(::grpc::ServerContext* context, const ::grewal::HomeGeneralRequest* request, ::grewal::HomeGeneralResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace grewal

