// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: home_general.proto
// Original file comments:
// File: services/grewalcc/home_general.proto (Final, Lean Version)
//
// Standard syntax declaration
#ifndef GRPC_home_5fgeneral_2eproto__INCLUDED
#define GRPC_home_5fgeneral_2eproto__INCLUDED

#include "home_general.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace grewal {

class HomeGeneral final {
 public:
  static constexpr char const* service_full_name() {
    return "grewal.HomeGeneral";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Defines a single Remote Procedure Call (RPC) named GetHomeGeneral.
    // For a call this function, a client MUST send a
    // `GeneralRequest` message and can EXPECT to receive a
    // `GeneralResponse` message in return. This is the API contract.
    virtual ::grpc::Status GetHomeGeneral(::grpc::ClientContext* context, const ::grewal::GeneralRequest& request, ::grewal::GeneralResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grewal::GeneralResponse>> AsyncGetHomeGeneral(::grpc::ClientContext* context, const ::grewal::GeneralRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grewal::GeneralResponse>>(AsyncGetHomeGeneralRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grewal::GeneralResponse>> PrepareAsyncGetHomeGeneral(::grpc::ClientContext* context, const ::grewal::GeneralRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grewal::GeneralResponse>>(PrepareAsyncGetHomeGeneralRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Defines a single Remote Procedure Call (RPC) named GetHomeGeneral.
      // For a call this function, a client MUST send a
      // `GeneralRequest` message and can EXPECT to receive a
      // `GeneralResponse` message in return. This is the API contract.
      virtual void GetHomeGeneral(::grpc::ClientContext* context, const ::grewal::GeneralRequest* request, ::grewal::GeneralResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetHomeGeneral(::grpc::ClientContext* context, const ::grewal::GeneralRequest* request, ::grewal::GeneralResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grewal::GeneralResponse>* AsyncGetHomeGeneralRaw(::grpc::ClientContext* context, const ::grewal::GeneralRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grewal::GeneralResponse>* PrepareAsyncGetHomeGeneralRaw(::grpc::ClientContext* context, const ::grewal::GeneralRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetHomeGeneral(::grpc::ClientContext* context, const ::grewal::GeneralRequest& request, ::grewal::GeneralResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grewal::GeneralResponse>> AsyncGetHomeGeneral(::grpc::ClientContext* context, const ::grewal::GeneralRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grewal::GeneralResponse>>(AsyncGetHomeGeneralRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grewal::GeneralResponse>> PrepareAsyncGetHomeGeneral(::grpc::ClientContext* context, const ::grewal::GeneralRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grewal::GeneralResponse>>(PrepareAsyncGetHomeGeneralRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetHomeGeneral(::grpc::ClientContext* context, const ::grewal::GeneralRequest* request, ::grewal::GeneralResponse* response, std::function<void(::grpc::Status)>) override;
      void GetHomeGeneral(::grpc::ClientContext* context, const ::grewal::GeneralRequest* request, ::grewal::GeneralResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::grewal::GeneralResponse>* AsyncGetHomeGeneralRaw(::grpc::ClientContext* context, const ::grewal::GeneralRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::grewal::GeneralResponse>* PrepareAsyncGetHomeGeneralRaw(::grpc::ClientContext* context, const ::grewal::GeneralRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetHomeGeneral_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Defines a single Remote Procedure Call (RPC) named GetHomeGeneral.
    // For a call this function, a client MUST send a
    // `GeneralRequest` message and can EXPECT to receive a
    // `GeneralResponse` message in return. This is the API contract.
    virtual ::grpc::Status GetHomeGeneral(::grpc::ServerContext* context, const ::grewal::GeneralRequest* request, ::grewal::GeneralResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetHomeGeneral : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetHomeGeneral() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetHomeGeneral() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHomeGeneral(::grpc::ServerContext* /*context*/, const ::grewal::GeneralRequest* /*request*/, ::grewal::GeneralResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetHomeGeneral(::grpc::ServerContext* context, ::grewal::GeneralRequest* request, ::grpc::ServerAsyncResponseWriter< ::grewal::GeneralResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetHomeGeneral<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetHomeGeneral : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetHomeGeneral() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grewal::GeneralRequest, ::grewal::GeneralResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grewal::GeneralRequest* request, ::grewal::GeneralResponse* response) { return this->GetHomeGeneral(context, request, response); }));}
    void SetMessageAllocatorFor_GetHomeGeneral(
        ::grpc::MessageAllocator< ::grewal::GeneralRequest, ::grewal::GeneralResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::grewal::GeneralRequest, ::grewal::GeneralResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetHomeGeneral() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHomeGeneral(::grpc::ServerContext* /*context*/, const ::grewal::GeneralRequest* /*request*/, ::grewal::GeneralResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetHomeGeneral(
      ::grpc::CallbackServerContext* /*context*/, const ::grewal::GeneralRequest* /*request*/, ::grewal::GeneralResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetHomeGeneral<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetHomeGeneral : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetHomeGeneral() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetHomeGeneral() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHomeGeneral(::grpc::ServerContext* /*context*/, const ::grewal::GeneralRequest* /*request*/, ::grewal::GeneralResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetHomeGeneral : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetHomeGeneral() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetHomeGeneral() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHomeGeneral(::grpc::ServerContext* /*context*/, const ::grewal::GeneralRequest* /*request*/, ::grewal::GeneralResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetHomeGeneral(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetHomeGeneral : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetHomeGeneral() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetHomeGeneral(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetHomeGeneral() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHomeGeneral(::grpc::ServerContext* /*context*/, const ::grewal::GeneralRequest* /*request*/, ::grewal::GeneralResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetHomeGeneral(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetHomeGeneral : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetHomeGeneral() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::grewal::GeneralRequest, ::grewal::GeneralResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::grewal::GeneralRequest, ::grewal::GeneralResponse>* streamer) {
                       return this->StreamedGetHomeGeneral(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetHomeGeneral() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetHomeGeneral(::grpc::ServerContext* /*context*/, const ::grewal::GeneralRequest* /*request*/, ::grewal::GeneralResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetHomeGeneral(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::grewal::GeneralRequest,::grewal::GeneralResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetHomeGeneral<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetHomeGeneral<Service > StreamedService;
};

}  // namespace grewal


#endif  // GRPC_home_5fgeneral_2eproto__INCLUDED
