// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: home_general.proto

#include "home_general.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace grewal {
PROTOBUF_CONSTEXPR GeneralRequest::GeneralRequest(
    ::_pbi::ConstantInitialized) {}
struct GeneralRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GeneralRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GeneralRequestDefaultTypeInternal() {}
  union {
    GeneralRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GeneralRequestDefaultTypeInternal _GeneralRequest_default_instance_;
PROTOBUF_CONSTEXPR GeneralResponse::GeneralResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.remote_ip_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.user_agent_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GeneralResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GeneralResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GeneralResponseDefaultTypeInternal() {}
  union {
    GeneralResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GeneralResponseDefaultTypeInternal _GeneralResponse_default_instance_;
}  // namespace grewal
static ::_pb::Metadata file_level_metadata_home_5fgeneral_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_home_5fgeneral_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_home_5fgeneral_2eproto = nullptr;

const uint32_t TableStruct_home_5fgeneral_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::grewal::GeneralRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::grewal::GeneralResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::grewal::GeneralResponse, _impl_.remote_ip_),
  PROTOBUF_FIELD_OFFSET(::grewal::GeneralResponse, _impl_.user_agent_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::grewal::GeneralRequest)},
  { 6, -1, -1, sizeof(::grewal::GeneralResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::grewal::_GeneralRequest_default_instance_._instance,
  &::grewal::_GeneralResponse_default_instance_._instance,
};

const char descriptor_table_protodef_home_5fgeneral_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022home_general.proto\022\006grewal\"\020\n\016GeneralR"
  "equest\"8\n\017GeneralResponse\022\021\n\tremote_ip\030\001"
  " \001(\t\022\022\n\nuser_agent\030\002 \001(\t2P\n\013HomeGeneral\022"
  "A\n\016GetHomeGeneral\022\026.grewal.GeneralReques"
  "t\032\027.grewal.GeneralResponseb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_home_5fgeneral_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_home_5fgeneral_2eproto = {
    false, false, 194, descriptor_table_protodef_home_5fgeneral_2eproto,
    "home_general.proto",
    &descriptor_table_home_5fgeneral_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_home_5fgeneral_2eproto::offsets,
    file_level_metadata_home_5fgeneral_2eproto, file_level_enum_descriptors_home_5fgeneral_2eproto,
    file_level_service_descriptors_home_5fgeneral_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_home_5fgeneral_2eproto_getter() {
  return &descriptor_table_home_5fgeneral_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_home_5fgeneral_2eproto(&descriptor_table_home_5fgeneral_2eproto);
namespace grewal {

// ===================================================================

class GeneralRequest::_Internal {
 public:
};

GeneralRequest::GeneralRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:grewal.GeneralRequest)
}
GeneralRequest::GeneralRequest(const GeneralRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  GeneralRequest* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:grewal.GeneralRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GeneralRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GeneralRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata GeneralRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_home_5fgeneral_2eproto_getter, &descriptor_table_home_5fgeneral_2eproto_once,
      file_level_metadata_home_5fgeneral_2eproto[0]);
}

// ===================================================================

class GeneralResponse::_Internal {
 public:
};

GeneralResponse::GeneralResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:grewal.GeneralResponse)
}
GeneralResponse::GeneralResponse(const GeneralResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GeneralResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.remote_ip_){}
    , decltype(_impl_.user_agent_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.remote_ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.remote_ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_remote_ip().empty()) {
    _this->_impl_.remote_ip_.Set(from._internal_remote_ip(), 
      _this->GetArenaForAllocation());
  }
  _impl_.user_agent_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.user_agent_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_user_agent().empty()) {
    _this->_impl_.user_agent_.Set(from._internal_user_agent(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:grewal.GeneralResponse)
}

inline void GeneralResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.remote_ip_){}
    , decltype(_impl_.user_agent_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.remote_ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.remote_ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.user_agent_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.user_agent_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

GeneralResponse::~GeneralResponse() {
  // @@protoc_insertion_point(destructor:grewal.GeneralResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GeneralResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.remote_ip_.Destroy();
  _impl_.user_agent_.Destroy();
}

void GeneralResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GeneralResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:grewal.GeneralResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.remote_ip_.ClearToEmpty();
  _impl_.user_agent_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GeneralResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string remote_ip = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_remote_ip();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "grewal.GeneralResponse.remote_ip"));
        } else
          goto handle_unusual;
        continue;
      // string user_agent = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_user_agent();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "grewal.GeneralResponse.user_agent"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GeneralResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:grewal.GeneralResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string remote_ip = 1;
  if (!this->_internal_remote_ip().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_remote_ip().data(), static_cast<int>(this->_internal_remote_ip().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "grewal.GeneralResponse.remote_ip");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_remote_ip(), target);
  }

  // string user_agent = 2;
  if (!this->_internal_user_agent().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_user_agent().data(), static_cast<int>(this->_internal_user_agent().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "grewal.GeneralResponse.user_agent");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_user_agent(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:grewal.GeneralResponse)
  return target;
}

size_t GeneralResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:grewal.GeneralResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string remote_ip = 1;
  if (!this->_internal_remote_ip().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_remote_ip());
  }

  // string user_agent = 2;
  if (!this->_internal_user_agent().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_user_agent());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GeneralResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GeneralResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GeneralResponse::GetClassData() const { return &_class_data_; }


void GeneralResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GeneralResponse*>(&to_msg);
  auto& from = static_cast<const GeneralResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:grewal.GeneralResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_remote_ip().empty()) {
    _this->_internal_set_remote_ip(from._internal_remote_ip());
  }
  if (!from._internal_user_agent().empty()) {
    _this->_internal_set_user_agent(from._internal_user_agent());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GeneralResponse::CopyFrom(const GeneralResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:grewal.GeneralResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GeneralResponse::IsInitialized() const {
  return true;
}

void GeneralResponse::InternalSwap(GeneralResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.remote_ip_, lhs_arena,
      &other->_impl_.remote_ip_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.user_agent_, lhs_arena,
      &other->_impl_.user_agent_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata GeneralResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_home_5fgeneral_2eproto_getter, &descriptor_table_home_5fgeneral_2eproto_once,
      file_level_metadata_home_5fgeneral_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace grewal
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::grewal::GeneralRequest*
Arena::CreateMaybeMessage< ::grewal::GeneralRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::grewal::GeneralRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::grewal::GeneralResponse*
Arena::CreateMaybeMessage< ::grewal::GeneralResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::grewal::GeneralResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
