---
# tasks file for the envoy role

- name: "Envoy | Ensure config directory exists"
  ansible.builtin.file:
    path: /etc/envoy
    state: directory
    mode: '0755'
  become: yes

- name: "Envoy | Deploy the dynamic Envoy bootstrap config"
  ansible.builtin.template:
    src: "envoy-bootstrap-dynamic.yaml"
    dest: "/etc/envoy/envoy-dynamic.yaml"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "Restart envoy service"

- name: "Envoy | Deploy Envoy systemd unit file"
  ansible.builtin.template:
    src: "envoy.service.j2"
    dest: "/etc/systemd/system/envoy.service"
    owner: "root"
    group: "root"
    mode: '0644'
  become: yes
  notify: "Restart envoy service"

- name: "Envoy | Ensure Envoy service is started and enabled"
  ansible.builtin.systemd:
    name: "envoy.service"
    state: started
    enabled: yes
  become: yes
