/* automatically generated by rust-bindgen 0.72.0 */

pub type __u8 = core::ffi::c_uchar;
pub type __u16 = core::ffi::c_ushort;
pub type __u32 = core::ffi::c_uint;
pub type __s64 = core::ffi::c_longlong;
pub type __u64 = core::ffi::c_ulonglong;
#[repr(C)]
#[repr(align(64))]
#[derive(Debug, Copy, Clone)]
pub struct latency_sample {
    pub magic: __u32,
    pub version: __u32,
    pub t_start: __u64,
    pub t_end: __u64,
    pub delta_ns: __u64,
    pub cpu_cycles: __u64,
    pub cpu_id: __u32,
    pub sample_rate: __u16,
    pub flags: __u8,
    pub padding_1: __u8,
    pub checksum: __u64,
    pub entropy_snapshot: __u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tsc_jitter_tracker {
    pub deltas: [__u64; 16usize],
    pub variance_q32: __u64,
    pub write_idx: __u8,
    pub padding: [__u8; 7usize],
}
#[repr(C)]
#[repr(align(128))]
#[derive(Debug, Copy, Clone)]
pub struct percpu_shard {
    pub canary: __u64,
    pub write_idx: __u32,
    pub sample_rate: __u32,
    pub total_packets: __u64,
    pub unsampled_packets: __u64,
    pub cycles_per_ns_avg: __u64,
    pub m2_variance: __s64,
    pub cusum_positive: __s64,
    pub _pad_hot: [__u8; 8usize],
    pub tsc_jitter: tsc_jitter_tracker,
    pub anomaly_count: __u32,
    pub _pad_hot2: [__u8; 44usize],
    pub histogram: [__u64; 24usize],
    pub last_update_ns: __u64,
    pub _pad_warm: [__u8; 56usize],
    pub samples: [latency_sample; 1024usize],
}
#[repr(C)]
#[repr(align(64))]
#[derive(Debug, Copy, Clone)]
pub struct arena_metadata {
    pub magic: __u32,
    pub version: __u32,
    pub num_cpus: __u32,
    pub reserved: __u32,
    pub padding: [__u8; 48usize],
}
