#![no_std]
#![allow(non_camel_case_types)]

/* 
 * The bindings module contains the translation 
 * generated by bindgen 0.72.0 on the GCC-GEM-A 
 * Iowa VM located in us-central-f
 */
pub mod bindings;

/* 
 * GRADE A RE-EXPORT
 * Pulling types to the top-level for cleaner loader code.
 */
pub use bindings::{arena_metadata, latency_sample, percpu_shard, tsc_jitter_tracker};

/* 
 * SEMANTIC CONSTANTS
 * Match the KW_ABI_MAGIC and KW_ABI_VERSION in common.h
 */
pub const KW_ABI_MAGIC: u32 = 0x4B57414C; // "KWAL"
pub const KW_ABI_VERSION: u32 = 7;

/*
 * THE SEMANTIC RULER (Static Assertions)
 * These verify the physical layout of the Broadwell target.
 */

// Verify latency_sample is exactly one cache line
const _: () = assert!(core::mem::size_of::<latency_sample>() == 64);
const _: () = assert!(core::mem::align_of::<latency_sample>() == 64);

// Verify percpu_shard size (512 bytes metadata + 65536 bytes samples)
// 66048 / 64 = 1032 cache lines exactly.
const _: () = assert!(core::mem::size_of::<percpu_shard>() == 66048);
const _: () = assert!(core::mem::align_of::<percpu_shard>() == 128);

/*
 * Helper functions for semantic validation at runtime.
 */
impl latency_sample {
    pub fn is_valid(&self) -> bool {
        self.magic == KW_ABI_MAGIC && self.version == KW_ABI_VERSION
    }
}
