# ansible/roles/grewal_cc_web/vars/main.yml
---
grewal_cc_web_container_name: "grewal-cc-web"
grewal_cc_web_image_repository: "grewal/grewal-cc-web"
grewal_cc_web_image_tag: "0.5.14"
docker_network_name: "grewalnet"
grewal_cc_web_container_port: 3000
grewal_cc_web_host_health_check_port: 3001
