// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package ebpfctrl

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type xdp_ip_blockerIpBlocklistMap struct {
	Type       uint32
	KeySize    uint32
	ValueSize  uint32
	MaxEntries uint32
	MapFlags   uint32
}

// loadXdp_ip_blocker returns the embedded CollectionSpec for xdp_ip_blocker.
func loadXdp_ip_blocker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Xdp_ip_blockerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdp_ip_blocker: %w", err)
	}

	return spec, err
}

// loadXdp_ip_blockerObjects loads xdp_ip_blocker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdp_ip_blockerObjects
//	*xdp_ip_blockerPrograms
//	*xdp_ip_blockerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdp_ip_blockerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdp_ip_blocker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdp_ip_blockerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_ip_blockerSpecs struct {
	xdp_ip_blockerProgramSpecs
	xdp_ip_blockerMapSpecs
	xdp_ip_blockerVariableSpecs
}

// xdp_ip_blockerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_ip_blockerProgramSpecs struct {
	XdpIpBlockerProg *ebpf.ProgramSpec `ebpf:"xdp_ip_blocker_prog"`
}

// xdp_ip_blockerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_ip_blockerMapSpecs struct {
	IpBlocklistMap *ebpf.MapSpec `ebpf:"ip_blocklist_map"`
}

// xdp_ip_blockerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdp_ip_blockerVariableSpecs struct {
}

// xdp_ip_blockerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdp_ip_blockerObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_ip_blockerObjects struct {
	xdp_ip_blockerPrograms
	xdp_ip_blockerMaps
	xdp_ip_blockerVariables
}

func (o *xdp_ip_blockerObjects) Close() error {
	return _Xdp_ip_blockerClose(
		&o.xdp_ip_blockerPrograms,
		&o.xdp_ip_blockerMaps,
	)
}

// xdp_ip_blockerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdp_ip_blockerObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_ip_blockerMaps struct {
	IpBlocklistMap *ebpf.Map `ebpf:"ip_blocklist_map"`
}

func (m *xdp_ip_blockerMaps) Close() error {
	return _Xdp_ip_blockerClose(
		m.IpBlocklistMap,
	)
}

// xdp_ip_blockerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadXdp_ip_blockerObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_ip_blockerVariables struct {
}

// xdp_ip_blockerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdp_ip_blockerObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdp_ip_blockerPrograms struct {
	XdpIpBlockerProg *ebpf.Program `ebpf:"xdp_ip_blocker_prog"`
}

func (p *xdp_ip_blockerPrograms) Close() error {
	return _Xdp_ip_blockerClose(
		p.XdpIpBlockerProg,
	)
}

func _Xdp_ip_blockerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdp_ip_blocker_bpfel.o
var _Xdp_ip_blockerBytes []byte
