---
- name: Configure base VM settings and services
  hosts: gcc-gem-a
  become: yes

  tasks:
    - name: Ensure grewal-backend systemd unit file is deployed
      ansible.builtin.template:
        src: grewal-backend.service.j2
        dest: /etc/systemd/system/grewal-backend.service
        owner: root
        group: root
        mode: '0644'
      notify: Reload systemd and restart grewal-backend # This triggers the handler by name/listen topic

    - name: Ensure grewal-backend service is started and enabled
      ansible.builtin.systemd:
        name: grewal-backend.service # The service name
        state: started               # Ensure the service is running
        enabled: yes                 # Ensure the service starts on boot

  handlers:
    - name: Reload systemd daemon                     # Task 1 within the handler sequence
      listen: "Reload systemd and restart grewal-backend" # Match the notify name
      ansible.builtin.systemd:
        daemon_reload: yes                           # Reloads systemd to read changes

    - name: Restart grewal-backend service             # Task 2 within the handler sequence
      listen: "Reload systemd and restart grewal-backend" # Match the notify name
      ansible.builtin.systemd:
        name: grewal-backend.service                 # Specify the service
        state: restarted                             # Restart the service
