# ~/src/gcc-ansible-wsl/ansible/configure_vm.yml
---
- name: Configure gcc-gem-a VM
  hosts: gcc-gem-a
  become: yes

  # Load vaulted variables (and potentially non-vaulted ones too)
  # Includes consul_bind_address from secrets.yml
  vars_files:
    - vars/secrets.yml

  roles:
    - node_exporter
    - prometheus    # <-- Added this line
    - consul
    - envoy
    - grewal-backend

  # ---- Handlers: Actions triggered by 'notify' ----
  handlers:
    # Handler for the grewal-backend role to reload consul config
    - name: Reload Consul Configuration
      listen: "Reload Consul Configuration"
      ansible.builtin.command: "consul reload -http-addr={{ consul_bind_address }}:8500"
      changed_when: true
      become: yes

    # Handler needed when systemd unit files change
    - name: Reload systemd daemon
      listen: "Reload systemd daemon"
      ansible.builtin.systemd:
        daemon_reload: yes
      become: yes

    # Handler to restart the consul service
    - name: Restart consul service
      listen: "Restart consul service"
      ansible.builtin.systemd:
        name: consul.service
        state: restarted
      become: yes

    # Handler to restart the prometheus service
    - name: Restart prometheus service
      listen: "Restart prometheus service"
      ansible.builtin.systemd:
        name: prometheus.service
        state: restarted
      become: yes
