---
- name: Ensure htop and vim are installed  # <-- Let's update the play name too
  hosts: gcc-gem-a
  become: yes

  tasks:
    - name: Install htop package
      ansible.builtin.apt:
        name: htop
        state: present
        update_cache: yes # update_cache:yes is only needed once per play usually

    - name: Install vim package
      ansible.builtin.apt:
        name: vim
        state: present
