# ~/src/gcc-gem-a/ansible/roles/envoy/handlers/main.yml
---
- name: Reload systemd and restart envoy
  ansible.builtin.systemd:
    name: envoy.service
    state: restarted
    daemon_reload: true # Ensure systemd reads the new unit file
  become: true # Run this task as root (sudo)
