---
# handlers file for envoy role

- name: Reload systemd daemon
  become: yes
  ansible.builtin.systemd:
    daemon_reload: yes
  listen: "Reload systemd daemon"

- name: Restart envoy service
  become: yes
  ansible.builtin.systemd:
    name: envoy.service
    state: restarted
  listen: "Restart envoy service"
