# .github/workflows/build-backend.yaml
name: Build, Test, and Deploy C++ Backend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test grewal binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Base Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            pkg-config \
            cmake \
            libgrpc++-dev \
            libprotobuf-dev \
            protobuf-compiler \
            protobuf-compiler-grpc \
            libre2-dev \
            libgflags-dev \
            libctemplate-dev \
            libgoogle-glog-dev \
            libabsl-dev \
            libssl-dev \
            zlib1g-dev \
            liblzma-dev \
            libunwind-dev \
            libgtest-dev \
            wget # Ensure wget is installed

      # STEP 1: Build c-ares and add DETAILED verification
      - name: Build c-ares from source with Verification
        run: |
          export CARES_VERSION="1.34.4" # Or use the version you intend
          export CARES_INSTALL_PREFIX="$GITHUB_WORKSPACE/cares_install"
          mkdir -p "$CARES_INSTALL_PREFIX"
          echo "Installing c-ares version ${CARES_VERSION} to $CARES_INSTALL_PREFIX"

          echo "Downloading c-ares source tarball (v${CARES_VERSION})..."
          wget -q -O "c-ares-${CARES_VERSION}.tar.gz" "https://github.com/c-ares/c-ares/releases/download/v${CARES_VERSION}/c-ares-${CARES_VERSION}.tar.gz"
          if [ ! -f "c-ares-${CARES_VERSION}.tar.gz" ]; then
             echo "ERROR: Failed to download c-ares tarball!"
             exit 1
          fi

          echo "Extracting c-ares source..."
          mkdir cares_src
          tar xzf "c-ares-${CARES_VERSION}.tar.gz" -C cares_src --strip-components=1
          cd cares_src

          echo "Configuring c-ares with CMake..."
          # Ensure the CMake build produces libcares.pc
          cmake . \
            -DCMAKE_INSTALL_PREFIX="$CARES_INSTALL_PREFIX" \
            -DCARES_STATIC=ON \
            -DCARES_SHARED=OFF \
            -DPC_FILENAME=libcares # Explicitly request libcares.pc if possible, though default might be this already
          echo "Building c-ares..."
          make -j$(nproc)
          echo "Installing c-ares..."
          make install # This installs files into $CARES_INSTALL_PREFIX

          # --- Verification ---
          echo "--- Checking installed c-ares files ---"
          echo "Searching for libcares.a:"
          find "$CARES_INSTALL_PREFIX" -name "libcares.a" -exec ls -l {} \; || echo "libcares.a NOT FOUND!"

          # Search specifically for libcares.pc now
          echo "Searching for libcares.pc and showing details:"
          find "$CARES_INSTALL_PREFIX" -name "libcares.pc" -exec ls -l {} \; -exec echo "--- Content of libcares.pc (if found): ---" \; -exec cat {} \; || echo "libcares.pc NOT FOUND!"

          echo "--- Listing contents of expected install directories ---"
          echo "Listing $CARES_INSTALL_PREFIX/lib:"
          ls -l "$CARES_INSTALL_PREFIX/lib" || echo "Directory $CARES_INSTALL_PREFIX/lib not found or empty."
          echo "Listing $CARES_INSTALL_PREFIX/lib/pkgconfig:"
          ls -l "$CARES_INSTALL_PREFIX/lib/pkgconfig" || echo "Directory $CARES_INSTALL_PREFIX/lib/pkgconfig not found or empty."
          echo "Listing $CARES_INSTALL_PREFIX/share/pkgconfig:"
          ls -l "$CARES_INSTALL_PREFIX/share/pkgconfig" || echo "Directory $CARES_INSTALL_PREFIX/share/pkgconfig not found or empty."

          cd .. # Go back to workspace root

      # STEP 2: Build Backend Binary with pkg-config debugging
      - name: Build Backend Binary with Debugging
        # Set PKG_CONFIG_PATH to where libcares.pc was installed
        env:
          PKG_CONFIG_PATH: ${{ github.workspace }}/cares_install/lib/pkgconfig # Verify this path from step 1 output
        run: |
          echo "--- Using PKG_CONFIG_PATH=$PKG_CONFIG_PATH ---"

          # --- Debugging pkg-config search for libcares ---
          echo "--- Running pkg-config --debug to trace search for libcares ---"
          pkg-config --debug --exists libcares || echo "pkg-config --debug --exists libcares FAILED (see output above)" # CHANGED c-ares to libcares

          echo "--- Checking pkg-config's own reported search path variable ---"
          pkg-config --variable pc_path pkg-config || echo "Could not get pkg-config search path variable"

          # --- Running main check for libcares ---
          echo "--- Running main check: pkg-config --exists --print-errors libcares ---"
          pkg-config --exists --print-errors libcares || (echo "ERROR: Final check failed - cannot find libcares via pkg-config using PKG_CONFIG_PATH=$PKG_CONFIG_PATH" && exit 1) # CHANGED c-ares to libcares

          echo "--- pkg-config check passed! Getting static libs flags for libcares: ---"
          pkg-config --static --libs libcares # CHANGED c-ares to libcares

          echo "--- Proceeding with make (verbose) ---"
          # Use V=1 for verbose make output to see the exact compile/link commands
          # The Makefile itself also needs to request 'libcares' now
          make -C frontend V=1

      # STEP 3: Run Tests
      - name: Run Tests
        env:
          # Pass the PKG_CONFIG_PATH here too, make test will invoke pkg-config via Makefile
          PKG_CONFIG_PATH: ${{ github.workspace }}/cares_install/lib/pkgconfig
          LD_LIBRARY_PATH: ${{ github.workspace }}/cares_install/lib # May not be needed for static, but harmless
        run: |
          echo "--- Running tests with PKG_CONFIG_PATH=$PKG_CONFIG_PATH ---"
          # Ensure the Makefile's test target also correctly uses libcares
          make -C frontend test

      # STEP 4: Check Binary Linkage and Size
      - name: Check Binary Linkage and Size
        run: |
          echo "--- Checking grewal binary ---"
          if [ -f frontend/grewal ]; then
            ls -lh frontend/grewal
            ldd frontend/grewal
          else
            echo "grewal binary not found (build likely failed)"
            exit 1
          fi

      # STEP 5: Upload Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: grewal-binary
          path: frontend/grewal
          if-no-files-found: warn

  # STEP 6: Deploy Job
  deploy:
    name: Deploy grewal binary to VM
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: grewal-binary

      - name: Set Execute Permissions
        run: chmod +x grewal

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Copy binary to VM
        run: >
          scp -o StrictHostKeyChecking=no \
          grewal \
          ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:~/grewal_new_deploy

      - name: Execute deployment script on VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
            echo "Stopping grewal service..."
            sudo /usr/bin/systemctl stop grewal.service
            echo "Copying new binary..."
            sudo /usr/bin/cp /home/${{ secrets.DEPLOY_USER }}/grewal_new_deploy /usr/local/bin/grewal
            echo "Setting permissions on new binary..."
            sudo chmod +x /usr/local/bin/grewal
            echo "Starting grewal service..."
            sudo /usr/bin/systemctl start grewal.service
            echo "Removing temporary file..."
            rm /home/${{ secrets.DEPLOY_USER }}/grewal_new_deploy
            echo "Checking service status..."
            sudo /usr/bin/systemctl status grewal.service --no-pager || true
          EOF
