name: Deploy Configuration via Ansible

on:
  push:
    branches:
      - master
      - envoy-security-service-dev
    paths:
      - 'ansible/**'
      - '.github/workflows/deploy-ansible-config.yaml'
      - 'services/security-service/go/**'
  workflow_dispatch: # Allows manual triggering

jobs:
  apply_playbook:
    name: Apply Ansible Playbook
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
      env:
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}

    - name: Install Ansible
      run: |
        sudo apt-get update && sudo apt-get install ansible -y

    - name: Test Vault Decryption in CI
      env:
        ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      run: |
        echo "Attempting to view vaulted file using --vault-password-file..."
        ansible-vault view --vault-password-file <(echo "$ANSIBLE_VAULT_PASSWORD") ansible/vars/secrets.yml
        echo "Vault view command finished."

    - name: Run ansible-playbook
      env:
        ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        ANSIBLE_HOST_KEY_CHECKING: false
        SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}
        SSH_AGENT_PID: ${{ env.SSH_AGENT_PID }}
      run: |
        echo "Running playbook with explicit vault password file..."
        ansible-playbook \
          -i ansible/inventory.ini \
          --vault-password-file <(echo "$ANSIBLE_VAULT_PASSWORD") \
          ansible/configure_vm.yml
