name: Build and Push Authz Service Docker Image

on:
  push:
    branches:
      - envoy-security-service-dev # Trigger on pushes to the dev branch
      # - master # Optionally uncomment when ready to push from master
    paths:
      - 'services/security-service/go/**' # Only run if Go code or Dockerfile changes
      - '.github/workflows/docker-publish-authz.yml' # Also run if workflow itself changes

jobs:
  build_and_push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Use an access token, not your password

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./services/security-service/go # Path to the directory containing the Dockerfile
          file: ./services/security-service/go/Dockerfile # Explicit path to the Dockerfile
          push: true # Actually push the image
          tags: | # Tags to apply to the image
            grewal/authz-service:latest
            grewal/authz-service:${{ github.sha }} # Tag with the specific commit SHA
          cache-from: type=gha # Enable GitHub Actions cache for build layers
          cache-to: type=gha,mode=max
