---
# tasks file for the 'grewalcc' C++ gRPC service

- name: Pull the specified grewalcc Docker image
  community.docker.docker_image:
    name: "{{ grewalcc_image_repository }}:{{ grewalcc_image_tag }}"
    source: pull
  become: yes
  tags:
    - grewalcc

- name: Ensure grewalcc container is running
  community.docker.docker_container:
    name: "{{ grewalcc_container_name }}"
    image: "{{ grewalcc_image_repository }}:{{ grewalcc_image_tag }}"
    state: started
    pull: false
    recreate: true
    restart_policy: always
    networks:
      - name: "{{ docker_network_name }}"
    ports:
      - "{{ grewalcc_container_port }}:{{ grewalcc_container_port }}"
    labels:
      service: "grewalcc"
      project: "grewal.cc"
  become: yes
  tags:
    - grewalcc

- name: Deploy Consul service definition for grewalcc
  ansible.builtin.template:
    src: grewalcc-service.hcl.j2
    dest: "/etc/consul.d/grewalcc-service.hcl"
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Reload Consul Configuration
  tags:
    - grewalcc
